//Generated by GenerateFieldArrayFormFromRelationship
import { Field, FieldArrayRenderProps, FormikProps } from "formik";
import React, {
  Dispatch,
  SetStateAction,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import {
  BudgetFormModel,
  BudgetModel,
} from "../../interfaces/BudgetInterfaces";
import {
  Stack,
  Table,
  TableHead,
  TableRow,
  TableCell,
  TableBody,
  Button,
  Typography,
  Checkbox,
  TextField,
  TableFooter,
} from "@mui/material";
import {
  MUICheckbox,
  MUIAutocomplete,
  MUIText,
  MUINumber,
} from "../../utils/formik";
import { TRequiredList } from "../../hooks/budget/useBudgetForm";
import Dialog from "../dialog/Dialog";
import { formatCurrency, parseAsValidFloat } from "../../utils/utilities";

type BudgetItemFormProp = {
  formik: FormikProps<BudgetFormModel>;
  arrayHelper: FieldArrayRenderProps;
  requiredListObject: TRequiredList;
  budget: BudgetModel | null;
  formHandlers: {
    handleSubmit: (values: BudgetFormModel) => Promise<void>;
    handleDelete: () => void;
    handleCancelClick: () => void;
    setDeletedBudgetItems: Dispatch<SetStateAction<number[]>>;
  };
  rowTotals: string[];
};

const BudgetItemForm: React.FC<BudgetItemFormProp> = ({
  formik,
  arrayHelper,
  requiredListObject,
  budget,
  formHandlers,
  rowTotals,
}) => {
  const checkedItems = formik.values.BudgetItems.filter(
    (item) => item.checked === true
  ).length;
  const s = checkedItems > 1 ? "s" : "";

  const dialogMessage = `${checkedItems} record${s} will be deleted. Do you want to proceed?`;

  //Generated by GetFormikArrayTotalComputation
  //Compute field totals for this record
  let total_amount = 0;
  formik.values.BudgetItems.forEach((item) => {
    total_amount += parseFloat(item.amount);
  });

  //This will handle the "Delete Selected Button"
  const handleDeleteChecked = () => {
    const deletedBudgetItems: number[] = [];
    const newArray = formik.values.BudgetItems.filter((item) => {
      if (!item.checked) {
        return true;
      } else {
        if (item.id !== "") {
          deletedBudgetItems.push(parseInt(item.id));
        }
      }
    });
    formik.setFieldValue("Decks", newArray);
    formHandlers.setDeletedBudgetItems(deletedBudgetItems);
    formik.handleSubmit();
  };

  const [toggleAllCheckbox, setToggleAllCheckbox] = useState<boolean>(false);
  const [focus, setFocus] = useState<number | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const handeToggleAllCheckbox = () => {
    formik.setFieldValue(
      "BudgetItems",
      formik.values.BudgetItems.map((item) => ({
        ...item,
        checked: !toggleAllCheckbox,
      }))
    );
    setToggleAllCheckbox(!toggleAllCheckbox);
  };

  //Generated by Generate_handleAddRowButtonClick
  //Generated by Generate_handleAddRowButtonClick
  const handleAddRowButtonClick = () => {
    arrayHelper.push({
      id: "",
      category: "Workday",
      type: "Income",
      amount: "0.00",
      description: "",
      checked: false,
      touched: false,
    });
    setFocus(Date.now());
  };

  const [openDialog, setOpenDialog] = useState(false);
  const handleCloseDialog = () => setOpenDialog(false);
  const handleOpenDialog = () => setOpenDialog(true);

  const dialogObject = { openDialog, handleCloseDialog, handleOpenDialog };

  useEffect(() => {
    if (inputRef.current && focus !== null) {
      inputRef.current.focus();
    }
  }, [focus]);

  return (
    <Stack direction="column" gap={2}>
      <Stack
        direction="row"
        gap={2}
        alignItems={"center"}
        justifyContent={"flex-end"}
        height={"30px"}
      >
        <Checkbox
          checked={toggleAllCheckbox}
          onChange={handeToggleAllCheckbox}
          size="small"
          tabIndex={-1}
        />
        {checkedItems > 0 && <Typography>{checkedItems}</Typography>}

        <Button
          variant="contained"
          color="error"
          size="small"
          onClick={dialogObject.handleOpenDialog}
          disabled={checkedItems === 0}
          sx={{ ml: "auto" }}
        >
          Delete Selected
        </Button>
      </Stack>
      <Table
        size="small"
        sx={{
          "& .MuiTableCell-root": {
            borderBottom: 0,
            fontSize: "inherit",
            lineHeight: "1rem",
            pl: 0,
            verticalAlign: "top",
          },
          "& tr td:last-child": {
            pr: 0,
          },
        }}
      >
        {/* Generated by GenerateFormikArrayTableHead */}
        <TableHead>
          <TableRow>
            <TableCell sx={{ width: "25px" }}></TableCell>
            {/* Generated by GenerateFieldTableCellHeader */}
            <TableCell sx={{ width: "200px" }}>Category</TableCell>
            {/* Generated by GenerateFieldTableCellHeader */}
            <TableCell sx={{ width: "200px" }}>Type</TableCell>
            {/* Generated by GenerateFieldTableCellHeader */}
            <TableCell align="right" sx={{ width: "150px" }}>
              Amount
            </TableCell>
            {/* Generated by GenerateFieldTableCellHeader */}
            <TableCell>Description</TableCell>
            <TableCell align="right" sx={{ width: "125px" }}>
              Total
            </TableCell>
          </TableRow>
        </TableHead>
        {/* Generated by GenerateFormikArrayControls */}
        <TableBody>
          {formik.values.BudgetItems.map((item, index) => (
            <TableRow key={index}>
              <TableCell>
                <MUICheckbox
                  name={`BudgetItems.${index}.checked`}
                  size="small"
                  tabIndex={-1}
                />
              </TableCell>
              <TableCell>
                {/* Generated by GenerateIndividualFormControlArray */}
                {requiredListObject.categories && (
                  <MUIAutocomplete
                    label=""
                    name={`BudgetItems.${index}.category`}
                    items={[
                      { id: "", name: "" },
                      ...requiredListObject.categories,
                    ]}
                    freeSolo={false}
                    multiple={false}
                    setArrayTouched={() => {
                      formik.setFieldValue(
                        `BudgetItems.${index}.touched`,
                        true
                      );
                    }}
                  />
                )}
              </TableCell>
              <TableCell>
                {/* Generated by GenerateIndividualFormControlArray */}
                {requiredListObject.types && (
                  <MUIAutocomplete
                    label=""
                    name={`BudgetItems.${index}.type`}
                    items={[{ id: "", name: "" }, ...requiredListObject.types]}
                    freeSolo={false}
                    multiple={false}
                    setArrayTouched={() => {
                      formik.setFieldValue(
                        `BudgetItems.${index}.touched`,
                        true
                      );
                    }}
                  />
                )}
              </TableCell>
              <TableCell>
                {/* Generated by GenerateIndividualFormControlArray */}
                <MUINumber
                  name={`BudgetItems.${index}.amount`}
                  label={""}
                  setArrayTouched={() => {
                    formik.setFieldValue(`BudgetItems.${index}.touched`, true);
                  }}
                />
              </TableCell>
              <TableCell>
                {/* Generated by GenerateIndividualFormControlArray */}
                <MUIText
                  name={`BudgetItems.${index}.description`}
                  label={""}
                  setArrayTouched={() => {
                    formik.setFieldValue(`BudgetItems.${index}.touched`, true);
                  }}
                  onKeyDown={(e: React.KeyboardEvent) => {
                    if (
                      formik.values.BudgetItems.length === index + 1 &&
                      e.key === "Tab"
                    ) {
                      e.preventDefault();
                      handleAddRowButtonClick();
                    }
                  }}
                />
              </TableCell>
              <TableCell>
                <TextField
                  value={rowTotals[index]}
                  disabled
                  size="small"
                  inputProps={{ style: { textAlign: "right" } }}
                  fullWidth
                />
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
        {/* Generated by GetFormikArrayTableFooterForTotal */}
      </Table>
      <Button size="small" variant="outlined" onClick={handleAddRowButtonClick}>
        Add Row
      </Button>
      <Dialog
        open={dialogObject.openDialog}
        message={dialogMessage}
        handleCloseDialog={dialogObject.handleCloseDialog}
        handleFunction={handleDeleteChecked}
      />
    </Stack>
  );
};

export default BudgetItemForm;
