//Generated by CreateModelForm
import React, { Dispatch, SetStateAction } from "react";
import { Alert, Box, Button, Container, Paper, Stack } from "@mui/material";
import { Field, FieldArray, Formik } from "formik";
import Link from "next/link";
import {
  BudgetItemFormModel,
  BudgetItemModel,
} from "../../interfaces/BudgetItemInterfaces";
import { TRequiredList } from "../../hooks/budgetItem/useBudgetItemForm";
import BudgetItemSchema from "../../schema/budgetItem/BudgetItemSchema";
import {
  ConvertBasicModelToControlChoice,
  ConvertNumberArrToControlChoice,
} from "../../utils/utilities";
import { MUIText, MUIRadio, MUIAutocomplete } from "../../utils/formik";


type BudgetItemFormProps = {
  budgetItem: BudgetItemModel | null;
  formInitialValues: BudgetItemFormModel;
  formHandlers: {
    handleSubmit: (values: BudgetItemFormModel) => Promise<void>;
    handleDelete: () => void;
    handleCancelClick: () => void;
    
  };
  requiredListObject: TRequiredList;
  handleOpenDialog: () => void;
  formError: string | null;
};

const BudgetItemForm: React.FC<BudgetItemFormProps> = ({
  budgetItem,
  formInitialValues,
  formHandlers,
  requiredListObject,
  handleOpenDialog,
  formError,
}) => {
  return (
    <Formik
      enableReinitialize={true}
      initialValues={formInitialValues}
      validateOnBlur={false}
      validateOnChange={false}
      validationSchema={BudgetItemSchema}
      onSubmit={formHandlers.handleSubmit}
    >
      {(formik) => {
        return (
          <Stack
            component="form"
            noValidate
            autoComplete="off"
            direction="column"
            onSubmit={formik.handleSubmit}
            spacing={2}
            p={2}
            sx={{
              "& .MuiFormHelperText-root": {
                fontSize: "0.70rem",
                ml: 1,
              },
              "& .MuiInputLabel-shrink": {
                fontSize: "1rem",
                bgcolor: "white",
                width: "auto",
                pr: 0.8,
                transform: "translate(14px, -11px) scale(0.75)",
              },
            }}
          >
            <Stack direction="column" gap={4}>
              {formError && <Alert severity="error">{formError}</Alert>}
              <Stack direction="column" gap={2}>
                {/* Generated by GenerateModelFormControls */}
{/* Generated by GenerateIndividualFormControl */}
<MUIText label="Budget" name="budget_id" type="number" />
{/* Generated by GenerateIndividualFormControl */}
{requiredListObject.categories && (
  <MUIAutocomplete
    label="Category"
    name="category"
    items={requiredListObject.categories}
    freeSolo={false}
    multiple={false}
  />
)}
{/* Generated by GenerateIndividualFormControl */}
{requiredListObject.types && (
  <MUIAutocomplete
    label="Type"
    name="type"
    items={requiredListObject.types}
    freeSolo={false}
    multiple={false}
  />
)}
{/* Generated by GenerateIndividualFormControl */}
<MUIText label="Amount" name="amount"  />
{/* Generated by GenerateIndividualFormControl */}
<MUIText label="Description" name="description"  />
              </Stack>
            </Stack>
            <Stack direction="row" gap={1}>
              <Button
                type="submit"
                size="small"
                color="primary"
                variant="contained"
                sx={{ width: 50 }}
              >
                Submit
              </Button>
              {Boolean(budgetItem) && (
                <Button
                  size="small"
                  color="error"
                  variant="contained"
                  sx={{ width: 50 }}
                  onClick={handleOpenDialog}
                >
                  Delete
                </Button>
              )}

              <Button type="submit" size="small" sx={{ width: 50 }}>
                <Link
                  href="/"
                  style={{ textDecoration: "none", color: "inherit" }}
                >
                  Cancel
                </Link>
              </Button>
            </Stack>
          </Stack>
        );
      }}
    </Formik>
  );
};

export default BudgetItemForm;
