//Generated by GenerateListHook
import { SelectChangeEvent } from "@mui/material";
import { FormikProps } from "formik";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import {
  BudgetURLQuery,
  BudgetFilterFormDefaultValue,
  BudgetModel,
} from "../../interfaces/BudgetInterfaces";
import {
  BasicModel,
  SortPair,
  NameCaption,
  SortOptions,
  SortOptionsAsString,
} from "../../interfaces/GeneralInterfaces";
import axiosClient from "../../utils/api";
import {
  getFilterValueFromURL,
  getParamsObject,
  getSortedBy,
  modifySort,
  modifyLimit,
  getFirstItem,
  getAxiosParams,
  supplyMissingNames,
  modifySortAsString,
} from "../../utils/utilities";
import usePromiseAll from "../usePromiseAll";
import { useToggle } from "../useToggle";
import { monthsModel } from "../../utils/constants";
//Generated by GetAdditionalImportBasedOnListVariableName
export interface TotalIncomeAndExpense {
  month: number;
  year: number;
  total_income: string;
  total_expense: string;
  net_income: string;
}

const useBudgets = (query: Partial<BudgetURLQuery>) => {
  const router = useRouter();
  //Generated by CopyAllEnumConstantDeclaration
  const months = monthsModel;
  //Generated by CopyUsePromiseAllOfThisModel

  const {
    data,
    loading: isRequiredListLoading,
    error: promiseAllError,
  } = usePromiseAll({});

  promiseAllError && console.log(promiseAllError);
  const requiredListObject: TRequiredList = { months, isRequiredListLoading }; //Generated by Build_requiredList
  //Generated by Generate_filterFormDefaultValue
  const filterFormDefaultValue: BudgetFilterFormDefaultValue = {
    year: "",
    month: "",
  };
  //Reshape the initial values of the filter form depending on the URL queries
  const filterFormInitialValue: BudgetFilterFormDefaultValue =
    getFilterValueFromURL(query, filterFormDefaultValue);
  //This will supply the name key for each array of objects
  //Generated by GenerateFilterFormikEvents
  const handleFilterFormSubmit = (values: BudgetFilterFormDefaultValue) => {
    const params = getParamsObject(
      values,
      filterFormDefaultValue
    ) as Partial<BudgetURLQuery>;
    router.push({ pathname: router.pathname, query: params });
  };

  const handleFilterFormReset = (formik: FormikProps<any>) => {
    formik.resetForm({
      values: filterFormDefaultValue,
    });
    router.push({ pathname: router.pathname });
  };
  const formikObject: TFormikFilterFormObject = {
    filterFormDefaultValue,
    filterFormInitialValue,
    handleFilterFormSubmit,
    handleFilterFormReset,
  };
  //Generated by GenerateClientModelSortLimit

  //Generated by GenerateClientSortOptions
  const sortedBy = getSortedBy(query, "-year,-month");
  const sortOptions: SortOptionsAsString = {
    sortedBy,
    sortObject: {
      period: { caption: "Period", asc: "year,month", desc: "-year,-month" },
    },
  };

  const handleBudgetSort = (name: string) =>
    modifySortAsString(name, sortOptions, router, query);

  const handleBudgetLimitChange = (event: SelectChangeEvent<string>) =>
    modifyLimit(event.target.value, router, query);

  const sortAndLimitObject = {
    limit: getFirstItem(query.limit, "20"),
    sortOptions,
    handleBudgetSort,
    handleBudgetLimitChange,
  };
  //Generated by GenerateMainListObject
  const [budgets, setBudgets] = useState<BudgetModel[]>([]);
  const [gridLoading, setGridLoading] = useState(true);
  const [recordCount, setRecordCount] = useState(0);

  const fetchBudgets = async () => {
    setGridLoading(true);

    try {
      const { data } = await axiosClient.get("/budgets/", {
        params: {
          ...getAxiosParams(query, filterFormDefaultValue),
          page: query.page,
          limit: query.limit,
          sort: query.sort,
        },
      });

      console.log({ data });

      if (data.data.status === "success" || data.status === "success") {
        const rows = data.data.rows || data.data;
        const count = data.data.count || data.totalRecordCount;
        setBudgets(rows || []);
        setRecordCount(count || 0);
      }
    } catch (error) {
      console.error(error);
    } finally {
      setGridLoading(false);
    }
  };

  const [totalIncomeAndExpenses, setTotalIncomeAndExpense] = useState<
    TotalIncomeAndExpense[] | null
  >(null);

  const fetchTotalIncomeAndExpense = async () => {
    try {
      const { data } = await axiosClient.get(
        "/budgets/get-total-income-and-expense-monthly"
      );

      if (data.status === "success") {
        const rows = data.data;
        setTotalIncomeAndExpense(rows);
      }
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    fetchBudgets();
  }, [query]);

  useEffect(() => {
    fetchTotalIncomeAndExpense();
  }, []);

  const mainListObject = { budgets, gridLoading, recordCount };
  //Generated by GenerateFilterFormToggleObject
  const { toggle: isFilterFormShown, handleToggle: toggleFilterForm } =
    useToggle();
  const toggleObject = { isFilterFormShown, toggleFilterForm };
  //Generated by GenerateListBreadcrumbLinks
  const breadCrumbLinks = [{ href: "/budgets", caption: "Budget List" }];
  return {
    requiredListObject,
    sortAndLimitObject,
    mainListObject,
    formikObject,
    toggleObject,
    breadCrumbLinks,
    totalIncomeAndExpenses,
  };
};
export type TMainListObject = {
  budgets: BudgetModel[];
  gridLoading: boolean;
  recordCount: number;
};
export type TFormikFilterFormObject = {
  filterFormDefaultValue: BudgetFilterFormDefaultValue;
  filterFormInitialValue: BudgetFilterFormDefaultValue;
  handleFilterFormSubmit: (values: BudgetFilterFormDefaultValue) => void;
  handleFilterFormReset: (formik: FormikProps<any>) => void;
};
export type TBudgetsHook = ReturnType<typeof useBudgets>;
//Generated by GenerateTRequiredListDeclaration
export type TRequiredList = {
  months: BasicModel[];
  isRequiredListLoading: boolean;
};
export default useBudgets;
